package nextstep.payments.data.repository

import nextstep.payments.data.model.Card

object PaymentCardsRepository {
    private val _cards = mutableListOf<Card>()
    val cards: List<Card> get() = _cards.toList()

    fun addCard(card: Card) {
        _cards.add(
            card.copy(id = autoGeneratedId())
        )
    }

    fun getCardOrNull(id: String): Card? {
        return _cards.firstOrNull { it.id == id }
    }

    fun modifyCard(id: String, card: Card) {
        _cards.indexOfFirst { it.id == id }.takeIf { index ->
            IntRange(0, _cards.size.dec()).contains(index)
        }?.let {
            _cards.set(
                it,
                card,
            )
        }
    }

    private fun autoGeneratedId() = "${_cards.size}"
}